### ISSUE TITLE
Can you add an option to show a projection based on current trends?

### ISSUE THREAD

**Issue by Leopere** [kennygrant/coronavirus#2]
I think that this would be even more effective at convincing people what’s happening if you show even a projection based on the current rate of progression and the average delay of testing to results lag because the data is at least 6 days out of sync apparently. Or at least mention the estimated delay and that the data may be significantly different.

**Comment by kennygrant** [comment]
I agree this would be a great idea, thinking about how to add it.

**Comment by Leopere** [comment]
That I’m not entirely sure on. But it would be pretty great!

**Comment by kennygrant** [comment]
I've added a growth chart here of deaths from day 2. 

https://coronavirus.projectpage.app/#growth

I'm hesitant to add projected growth to that chart as there are so many variables, but it does give a good idea of relative progress. Hope that is useful.
